### ISSUE TITLE
wrong use of log_det()

### ISSUE THREAD

**Issue by conradsnicta** [lbybee/changepoints#1]
@lbybee - In the file https://github.com/lbybee/changepoints/blob/master/src/changepoints.cpp
the log_det() function is used incorrectly:
    `float det0 = log_det(val, sign, theta0);`

According to Armadillo documentation, log_det() does not return the determinant like that.  You might be confusing det() with log_det().  http://arma.sourceforge.net/docs.html#det

The line should be:
    `double det0;  log_det(det0, sign, theta0);`

**Comment by lbybee** [comment]
Should be fixed now.  Thanks.
